FROM python:3.9-slim-buster AS py3
FROM openjdk:17-slim-buster

COPY --from=py3 / /
COPY Pipfile /
COPY Pipfile.lock /

RUN pip install pipenv
RUN pipenv install --dev
ENV PYSPARK_PYTHON=python3

WORKDIR /app

COPY test/ ./test/
# this image is 503mb (compressed) in ECR