version: "3.9"

services:
  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - $PWD/etc/catalog:/etc/trino/catalog

networks:
  trino-network:
    driver: bridge