name: Prod Test - PR

on:
  pull_request:

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
        run: |
          make docker-build
      - name: Run Tests
        run: |
          make docker-test