name: CI Pipeline

on:
  pull_request:

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Tests
        run: make test
